<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MembersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('members')->insert
        ([
            ['members_name' => 'Gawr Gura',
            'members_nickname' => 'Same-chan',
            'members_greet' => 'a',
            'members_title' => 'Gawr Gura (がうる・ぐら) is a female English-speaking Virtual YouTuber associated with hololive, debuting in 2020 as part of hololive English first generation "-Myth-" alongside Ninomae Ina, Takanashi Kiara, Watson Amelia and Mori Calliope.',
            'members_debutdate' => 'September 13, 2020',
            'members_profile' => 'A descendant of the Lost City of Atlantis, who swam to Earth while saying, "It so boring down there LOLOLOL!" Gura bought her clothes (and her shark hat) in the human world and she really loves them. In her spare time, she enjoys talking to marine life.',
            'members_personality' => 'Gura is friendly and readily likeable, and often amuses her viewers with foolish antics. She has no sense of direction, often misspells and mispronounces words, has trouble remembering her own age, and consistently fails to solve basic math problems, leading viewers to affectionately call her a "dum shark". Memorably, one viewer declared that "Gura has a heart of gold and a head of bone."',
            'members_img_icon' => 'Gawr_Gura_-_Portrait_01.png',
            'members_img_costume' => '1707419598.png',
            'members_img_costume2'=> '1707419598.png',
            'members_img_artwork' => '1707419598.png',
            'members_img_concept' => '1707419598.png',
            'members_introduction_video' => 'https://www.youtube.com/embed/dBK0gKW61NU',
            'members_name_Illustrator' => 'Amashiro Natsuki',
            'members_youtube' => 'https://www.youtube.com/channel/UCoSrY_IQQVpmIRZ9Xf-y93g',
            'members_youtube_name' => 'Gawr Gura Ch. hololive-EN',
            'generation_id' => '1',
            'affiliation_id' => '2',
            'gender_id' => '1',
            'ch' => 'Gawr Gura',],

            ['members_name' => 'Mori Calliope',
            'members_nickname' => 'Calli',
            'members_greet' => 'Guh!',
            'members_title' => 'Mori Calliope (森 カリオペ) is a female English-speaking Virtual YouTuber associated with hololive, debuting in 2020 as part of hololive English first generation "-Myth-" alongside Ninomae Ina, Takanashi Kiara, Watson Amelia and Gawr Gura.',
            'members_debutdate' => 'September 12, 2020',
            'members_profile' => 'The Grim Reaper first apprentice. Because the world medical system advanced so dramatically, Calliope became a VTuber to collect souls. It seems that the lost souls vaporized by the wholesome relationships of VTubers flow through her as well. In the end, she a gentle-hearted girl whose sweet voice contradicts the morbid things she tends to say, as well as her hardcore vocals.',
            'members_personality' => 'The Grim Reaper apprentice has displayed throughout her streams, guest appearances, and music to a have cool, yet serious personality, with a timid side being seen when interacting with others for the first time, such as her senpais. Calli cool attitude can be clearly observed in most of her streams, as she tries her best to impress her fans with her musical talent and occasional gaming skills.',
            'members_img_icon' => '435px-Mori_Calliope_-_Portrait_0.png',
            'members_img_costume' => 'Mori_Calliope_-_Full_Illustration_01.png',
            'members_img_costume2'=> 'Mori_Calliope_-_Full_Illustration_04.jpg',
            'members_img_artwork' => 'Full_Album_Cover_Art_-_Off_With_Their_Heads.jpg',
            'members_img_concept' => 'Mori_Calliope_-_Concept_Illustration_01.jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/M1_GeIfn48M',
            'members_name_Illustrator' => 'Yukisame',
            'members_youtube' => 'https://www.youtube.com/channel/UCL_qhgtOy0dy1Agp8vkySQg',
            'members_youtube_name' => 'Mori Calliope Ch. hololive-EN',
            'generation_id' => '1',
            'affiliation_id' => '2',
            'gender_id' => '1',
            'ch' => 'Mori Calliope',],

            ['members_name' => 'Takanashi Kiara',
            'members_nickname' => 'Kusotori',
            'members_greet' => 'Kikkerikiii!',
            'members_title' => 'Takanashi Kiara (小鳥遊キアラ) is a female English-speaking Virtual YouTuber associated with hololive, debuting in 2020 as part of hololive English first generation "-Myth-" alongside Ninomae Ina, Watson Amelia, Mori Calliope and Gawr Gura.',
            'members_debutdate' => 'September 12, 2020',
            'members_profile' => 'An idol whose dream is to become a fast food shop owner. Kiara is a phoenix, NOT a chicken or turkey. (Very important) She works extremely hard since she will be reborn from ashes anyway.',
            'members_personality' => 'Kiara is enthusiastic, energetic, passionate, and friendly, and is open with her feelings. She cares strongly for her friends and family, and misses them a great deal while she is abroad. She has seemingly no trouble holding a conversation with other ch, both within and outside of hololive. Kiara has no problem taking the lead in collaborations, and performing as host whenever the situation calls for it. Her energetic personality is also prevalent in her original songs, most notably SPARKS and HINOTORI, as they both have fast-paced beats and lyrics that feature an encouraging and positive message.',
            'members_img_icon' => 'Takanashi_Kiara_-_Portrait_01.png',
            'members_img_costume' => 'Takanashi_Kiara_-_Full_Illustration_01-1.png',
            'members_img_costume2'=> 'Takanashi_Kiara_-_Full_Illustration_03.png',
            'members_img_artwork' => 'Illustrator_Artwork_-_Takanashi_Kiara_05.jpg',
            'members_img_concept' => 'Takanashi_Kiara_-_Concept_Illustration_01.jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/uObh73QZUvg',
            'members_name_Illustrator' => 'huke',
            'members_youtube' => 'https://www.youtube.com/@TakanashiKiara/videos',
            'members_youtube_name' => 'Takanashi Kiara Ch. hololive-EN',
            'generation_id' => '1',
            'affiliation_id' => '2',
            'gender_id' => '1',
            'ch' => 'Takanashi Kiara',],

            ['members_name' => 'Ninomae Ina',
            'members_nickname' => 'Ina',
            'members_greet' => 'Wah.',
            'members_title' => 'Ninomae Ina (一伊那尓栖/にのまえいなにす) is a female English-speaking Virtual YouTuber associated with hololive, debuting in 2020 as part of hololive English first generation "-Myth-" alongside Takanashi Kiara, Watson Amelia, Mori Calliope and Gawr Gura.',
            'members_debutdate' => 'September 13, 2020',
            'members_profile' => 'One day, Ina picked up a strange book and then started to gain the power of controlling tentacles. To her, tentacles are just a part in her ordinary life; it has never been a big deal for her. However, her girly mind does want to get them dressed up and stay pretty. After gaining power, she started hearing Ancient Whispers and Revelations. Hence, she began her VTuber activities to deliver random sanity checks on humanity, as an ordinary girl',
            'members_personality' => 'Ina is a gentle, peaceful, soft-spoken and down-to-earth girl with an easy-going temperament, so much so that she reverses stress and insanity in her viewers rather than encouraging it, despite her Lovecraftian role as "the maiden who speaks for the old gods." She is very loving and aware towards her fellow members, capable of talking extensively about each one and their respective quirks.',
            'members_img_icon' => 'Ninomae_Inanis_-_Portrait_01-1.png',
            'members_img_costume' => 'Ninomae_Ina_-_Full_Illustration_01.png',
            'members_img_costume2'=> 'latest (10).png',
            'members_img_artwork' => 'Illustrator_Artwork_02.jpg',
            'members_img_concept' => 'Ninomae_Inana_-_Concept_Illutration_-_01.jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/ujCxiHpVYmg',
            'members_name_Illustrator' => 'Kuroboshi Kouhaku',
            'members_youtube' => 'https://www.youtube.com/@NinomaeInanis/videos',
            'members_youtube_name' => 'Ninomae Ina Ch. hololive-EN',
            'generation_id' => '1',
            'affiliation_id' => '2',
            'gender_id' => '1',
            'ch' => 'Ninomae Ina',],

            ['members_name' => 'Watson Amelia',
            'members_nickname' => 'Ame',
            'members_greet' => '#1 Detective',
            'members_title' => 'Watson Amelia (ワトソン・アメリア) is a female English-speaking Virtual YouTuber associated with hololive, debuting in 2020 as part of hololive English first generation "-Myth-" alongside Ninomae Ina, Takanashi Kiara, Mori Calliope and Gawr Gura.',
            'members_debutdate' => 'September 13, 2020',
            'members_profile' => 'Amelia heard strange rumors surrounding Hololive online: talking foxes, magical squirrels, superhuman dogs, and more. Soon after beginning her investigation on Hololive, and just out of interest, she decided to become an idol herself! She loves to pass her time training her reflexes with FPS games, and challenging herself with puzzle games. It elementary, right?',
            'members_personality' => 'Amelia is a highly eccentric girl who is often seen mingling or teasing her fellow holoMyth members. She is usually kind, supportive, and sweet as shown when she frequently watches her fellow members streams and often willingly helps Gura in Minecraft. She was said to have helped troubleshoot some of the technical problems her genmates were having before and during debut which led to the birth to the meme Amelia Tech Tips which is a parody of the popular YouTube channel Linus Tech Tips. Amelia is also highly supportive towards hololive members and frequently comments in any ongoing streams whenever she gets the time to do so.',
            'members_img_icon' => '900px-Watson_Amelia_-_Portrait_0.png',
            'members_img_costume' => 'Watson_Amelia_-_Full_Illustration_01.png',
            'members_img_costume2'=> 'Watson_Amelia_-_Full_Illustration_04-1.jpg',
            'members_img_artwork' => 'Illustrator_Artwork_-_Watson_Amelia_03.png',
            'members_img_concept' => 'Watson_Amelia_-_Concept_Illustration_01.jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/MXrFrkIlE-0',
            'members_name_Illustrator' => 'Aoi Nabi',
            'members_youtube' => 'https://www.youtube.com/@WatsonAmelia/videos',
            'members_youtube_name' => 'Watson Amelia Ch. hololive-EN',
            'generation_id' => '1',
            'affiliation_id' => '2',
            'gender_id' => '1',
            'ch' => 'Watson Amelia',],

            ['members_name' => 'Nanashi Mumei',
            'members_nickname' => 'Hoomans',
            'members_greet' => 'Oh hi',
            'members_title' => 'Nanashi Mumei (七詩ムメイ) is a female English speaking Virtual YouTuber associated with hololive. She debuted in 2021 as part of hololive -Council-, the second generation of members of hololive English, alongside Tsukumo Sana, Ceres Fauna, Ouro Kronii and Hakos Baelz.',
            'members_debutdate' => 'August 23, 2021',
            'members_profile' => 'The Guardian of Civilization, a traveling owl who has borne witness to numerous events.Even though glimpses of past memories—seen and forgotten throughout her endless journey—occasionally surface, she is now a lovely girl who relishes each and every day. When once she was just an observer, she now enjoys her everyday interactions with civilizations and its people.And soon the ordinary, ever-present daily life, shall also weave itself into the tapestry of civilization.',
            'members_personality' => 'At debut, Mumei gave the impression of a cheerful, gentle girl who is soft-spoken and somewhat innocent, especially when compared to her peers. She was initially very shy and often visibly nervous during streams.However, as she has gained confidence in streaming, a different persona has emerged. Mumei streams are now characterized by the duality between a relatively low energy, relaxing, and comfortable tone to another side which is more spontaneous and energetic; with her often demonstrating psychopathic tendencies in these moments. Though the disparity between her macabre thoughts and cute voice surprised many at first, the line separating these two sides has since blurred to a point of seamlessness with Mumei appreciation of the grotesque and ‘cursed’ being wholly embraced by Hoomans today.',
            'members_img_icon' => 'Nanashi_Mumei_-_Portrait_01.png',
            'members_img_costume' => 'Nanashi_Mumei_-_Full_Illustration_01.png',
            'members_img_costume2'=> 'Nanashi_Mumei_-_Full_Illustratio.png',
            'members_img_artwork' => 'IllustratorArtworkNanashiMumei.jpg',
            'members_img_concept' => 'Nanashi_Mumei_-_Concept_Illustration_01.jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/M2gwJ-7s0Zo',
            'members_name_Illustrator' => 'Azure',
            'members_youtube' => 'https://www.youtube.com/channel/UC3n5uGu18FoCy23ggWWp8tA',
            'members_youtube_name' => 'Nanashi Mumei Ch. hololive-EN',
            'generation_id' => '2',
            'affiliation_id' => '2',
            'gender_id' => '1',
            'ch' => 'Nanashi Mumei',],

            ['members_name' => 'Ouro Kronii',
            'members_nickname' => 'Kronini',
            'members_greet' => 'Gwak!',
            'members_title' => 'Ouro Kronii (オーロ・クロニー) is a female English speaking Virtual YouTuber associated with hololive. She debuted in 2021 as part of hololive -Council-, the second generation of members of hololive English, alongside Tsukumo Sana, Ceres Fauna, Nanashi Mumei and Hakos Baelz.',
            'members_debutdate' => 'August 23, 2021',
            'members_profile' => 'Time is an unwavering, precise entity, and its Warden - its overseer - is equally cool and impeccable. Occasionally her exquisiteness leads her to decisions and bouts of luck that transcend the understanding of mere mortals. However, even utmost perfection finds no foothold in the face of her mortal enemy—disorder.',
            'members_personality' => 'Ouro Kronii is very confident, self-centered, and completely unafraid to praise herself. However, she also describes herself as someone who is generally not a happy person, to the point of listing "existential dread" as a hobby. Kronii can be playful at times, especially with her Kronies, and the combination of her deadpan humor and dry delivery of jokes contrasts many of the other members who are either more outgoing or gentler with their words.',
            'members_img_icon' => 'Ouro_Kronii_-_Portrait_01.png',
            'members_img_costume' => 'Ouro_Kronii_-_Full_Illustration_01.png',
            'members_img_costume2'=> 'latest (101).png',
            'members_img_artwork' => 'Illustrator_Artwork_-_Ouro_Kronii_03.jpg',
            'members_img_concept' => 'Ouro_Kronii_-_Concept_Illustration_01.jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/W3oVrq94mGM',
            'members_name_Illustrator' => 'WADARCO',
            'members_youtube' => 'https://www.youtube.com/channel/UCmbs8T6MWqUHP1tIQvSgKrg',
            'members_youtube_name' => 'Ouro Kronii Ch. hololive-EN',
            'generation_id' => '2',
            'affiliation_id' => '2',
            'gender_id' => '1',
            'ch' => 'Ouro Kronii',],

            ['members_name' => 'Hakos Baelz',
            'members_nickname' => 'Bae',
            'members_greet' => 'WAZZUP!!',
            'members_title' => 'Hakos Baelz (ハコス・ベールズ) is a female English speaking Virtual YouTuber associated with hololive. She debuted in 2021 as part of hololive -Council-, the second generation of members of hololive English, alongside Tsukumo Sana, Ceres Fauna, Ouro Kronii and Nanashi Mumei.',
            'members_debutdate' => 'August 23, 2021',
            'members_profile' => 'Baelz is loud, unpredictable, and chaotic. Despite this, she seems to have a talent for leading off in discussions and keeping things as orderly as possible, as seen in the first hololive -Council- meeting. Ceres Fauna even described her as a natural born leader, and Baelz eventually embraced the role of "Leader of -Council-." In contrast to her chaotic nature, she speaks rather fondly of the other -Council- members, and is regarded by them as adorable in turn. Baelz can also be easily flustered if things do not go her way.',
            'members_personality' => 'A member of the Council and the very concept of Chaos, birthed by the world, itself. The Gods appointed her Chairperson of the Council, but she mostly takes a hands-off approach as she has yet to accept the decision, much like her fellow members. That said, all of them have no intention of contending; instead to obey.',
            'members_img_icon' => 'Hakos_Baelz_-_Portrait_01.png',
            'members_img_costume' => 'Hakos_Baelz_-_Full_Illustration_01.png',
            'members_img_costume2'=> '1000 (2).png',
            'members_img_artwork' => 'Illustrator_Artwork_-_Hakos_Baelz_02.jpg',
            'members_img_concept' => 'Hakos_Baelz_-_Concept_Illustration_01.jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/mJwpVT1WvLg',
            'members_name_Illustrator' => 'Mika Pikazo',
            'members_youtube' => 'https://www.youtube.com/@HakosBaelz/videos',
            'members_youtube_name' => 'Hakos Baelz Ch. hololive-EN',
            'generation_id' => '2',
            'affiliation_id' => '2',
            'gender_id' => '1',
            'ch' => 'Hakos Baelz',],

            ['members_name' => 'Hoshimachi Suisei',
            'members_nickname' => 'Sui-chan',
            'members_greet' => 'Hi... Honey~',
            'members_title' => 'Hoshimachi Suisei (星街すいせい) is a female Japanese Virtual YouTuber associated with hololive. Originally an independent VTuber who eventually was recruited into hololive production label INoNaKa Music, she was transferred to the main hololive branch on 1 December 2019. She is currently part of hololive 0th gen alongside fellow solo debutants: Tokino Sora, Roboco, Sakura Miko and AZKi.',
            'members_debutdate' => 'March 22, 2018 ',
            'members_profile' => 'It your shooting star, your diamond in the rough, idol VTuber Hoshimachi Suisei! A forever 18 VTuber who deeply loves singing and idols.Her dream is to one day hold a live concert in Tokyo Budokan.',
            'members_personality' => 'Suisei is a modest, multi-talented singer and aspiring idol who is among the more level-headed members of hololive, though she also has a childish streak. After her unexpectedly compelling performance as a traitor in a game of Project Winter, she gained a reputation for remorseless sociopathy behind a facade of polite sweetness.No one seems to know how much of the "Psychopath Suisei" persona is real or not, but Suisei herself acknowledges that it is extremely funny and has referred to the incident on multiple occasions.',
            'members_img_icon' => 'Hoshimach.png',
            'members_img_costume' => 'Hoshimachi_Suisei_-_Full_Illustration_04 (1).png',
            'members_img_costume2'=> 'Hoshimachi_Suisei_-_Full_Illustration_05.jpg',
            'members_img_artwork' => 'Illustrator_Artwork_-_Hoshimachi_Suisei_2nd_Anniversary (1).jpg',
            'members_img_concept' => 'Hoshimachi_Suisei_-_Concept_Illustration_04 (1).jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/1dOyVEls4pg',
            'members_name_Illustrator' => 'Teshima Nari',
            'members_youtube' => 'https://www.youtube.com/channel/UC5CwaMl1eIgY8h02uZw7u8A',
            'members_youtube_name' => 'Suisei Channel',
            'generation_id' => '4',
            'affiliation_id' => '1',
            'gender_id' => '1',
            'ch' => 'Hoshimachi Suisei',],

            ['members_name' => 'Shirakami Fubuki',
            'members_nickname' => 'Fubu-chan',
            'members_greet' => 'Friend',
            'members_title' => 'Shirakami Fubuki (白上フブキ) is a female Japanese Virtual Youtuber associated with hololive, debuting as part of its first generation of VTubers alongside Yozora Mel, Aki Rosenthal, Natsuiro Matsuri and Akai Haato',
            'members_debutdate' => 'June 1, 2018',
            'members_profile' => '"Good foxy day! I m Shirakami Fubuki!" White-haired animal-eared otaku fox. She loves talking with people and will be happy if you give her the time of day. She aims to become a top otaku idol while enjoying each and every day.',
            'members_personality' => 'Fubuki is usually always cheerful and excited, singing little songs and making many in-jokes. She is shy when confronted with new circumstances, and when embarrassed she "hides" at the bottom of the screen with only her fox ears peeking up. She becomes enthralled in games and has cute conversations with scripted game characters, or voice acts as characters while making effects.',
            'members_img_icon' => 'Shirakami_Fubuki_-_Portrait_01.png',
            'members_img_costume' => 'Shirakami_Fubuki_-_Full_Illustration_01.jpg',
            'members_img_costume2'=> 'Shirakami_Fubuki_-_Full_Illustration_04.png',
            'members_img_artwork' => 'Illustrator_Artwork_-_Shirakami_Fubuki_Birthday_2020.jpg',
            'members_img_concept' => 'Blue_Journey_-_Concept_Illustration_01.jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/LP5phg8T1YY',
            'members_name_Illustrator' => 'Nagishiro Mito',
            'members_youtube' => 'https://www.youtube.com/channel/UCdn5BQ06XqgXoAxIhbqw5Rg',
            'members_youtube_name' => 'フブキCh。白上フブキ',
            'generation_id' => '5',
            'affiliation_id' => '1',
            'gender_id' => '1',
            'ch' => 'Shirakami Fubuki',],

            ['members_name' => 'Hakui Koyori',
            'members_nickname' => 'The Researcher',
            'members_greet' => 'Not cat',
            'members_title' => 'Hakui Koyori (博衣こより) is a female Japanese Virtual YouTuber associated with hololive, debuting as part of its sixth generation under the name of "Secret Society holoX" alongside La+ Darknesss, Takane Lui, Sakamata Chloe and Kazama Iroha.',
            'members_debutdate' => '',
            'members_profile' => 'The one in charge of R&D in Secret Society holoX. As part of her studies into human behavior, she meddles in the other members affairs and tries to help them out at every turn. Possessed by an insatiable thirst for knowledge, she may sometimes also deliberately mess with people just to see how they react.The self-proclaimed "brains of the operation." Her areas of expertise, however, are pretty limited.',
            'members_personality' => 'Koyori is an energetic and cheerful person, similar to Shirakami Fubuki. Initially, she was considered by some fans as one of the most "seiso" members out of her generation along with Kazama Iroha, but this has since been negated when she started showing her perverted side, such as occasional drops of innuendos and knowledge in NSFW fictions.',
            'members_img_icon' => 'Hakui_Koyori_-_Portrait_01.png',
            'members_img_costume' => 'Hakui_Koyori_-_Full_Illustration_01.png',
            'members_img_costume2'=> 'koyori.png',
            'members_img_artwork' => 'hakui_koyori_hakui_koyori_and.png',
            'members_img_concept' => 'Hakui_Koyori_Concept_Art_01.jpg',
            'members_introduction_video' => 'https://www.youtube.com/embed/r3Ba-2Y5HDY',
            'members_name_Illustrator' => 'Momoco',
            'members_youtube' => 'https://www.youtube.com/channel/UC6eWCld0KwmyHFbAqK3V-Rw',
            'members_youtube_name' => 'Koyori ch. 博衣こより - holoX -',
            'generation_id' => '10',
            'affiliation_id' => '1',
            'gender_id' => '1',
            'ch' => 'Hakui Koyori',],
            

        ]);
    }
}
